// version.h
#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 2
#define PROJECT_VERSION_PATCH 0

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define PROJECT_VERSION TOSTRING(PROJECT_VERSION_MAJOR) "." TOSTRING(PROJECT_VERSION_MINOR) "." TOSTRING(PROJECT_VERSION_PATCH)
